# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1357702419);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1357702539);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1357807892);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1357808012);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 81920);
user_pref("browser.migration.version", 8);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 2);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.rights.3.shown", true);
user_pref("browser.startup.homepage", "http://www.susper.com");
user_pref("browser.startup.homepage_override.buildID", "20130107224806");
user_pref("browser.startup.homepage_override.mstone", "18.0");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "globalmenu%40ubuntu.com:3.6.4,ubufox%40ubuntu.com:2.6,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:18.0");
user_pref("extensions.installCache", "[{\"name\":\"app-system-share\",\"addons\":{\"ubufox@ubuntu.com\":{\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com\",\"mtime\":1357705454000}}},{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/firefox/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1357705453000},\"globalmenu@ubuntu.com\":{\"descriptor\":\"/usr/lib/firefox/extensions/globalmenu@ubuntu.com\",\"mtime\":1357705453000}}}]");
user_pref("extensions.lastAppVersion", "18.0");
user_pref("extensions.lastPlatformVersion", "18.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/plugin");
user_pref("extensions.ui.locale.hidden", true);
user_pref("gecko.buildID", "20130107224806");
user_pref("gecko.mstone", "18.0");
user_pref("idle.lastDailyNotification", 1357702601);
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.database.lastMaintenance", 1357702601);
user_pref("places.history.expiration.transient_current_max_pages", 19649);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1357702601);
user_pref("toolkit.startup.last_success", 1357872923);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1360294273);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
user_pref("xpinstall.whitelist.add.36", "");
