#!/bin/sh

set -e

MOZ_APP_NAME=firefox

if [ "$1" = "remove" ] ; then
    update-alternatives --remove gnome-www-browser /usr/bin/$MOZ_APP_NAME
    update-alternatives --remove x-www-browser /usr/bin/$MOZ_APP_NAME
fi


