#!/bin/bash

# Starting the script
echo "Starting aptRepoUpdater authored by Abishek V Ashok with love for FOSSASIA"
echo "..."

# Create the new directory to work in, these will get cleaned by Travis so no worries
mkdir work
cd work

# Adding configurations for git
git config --global user.email "travis@travis-ci.org"
git config --global user.name "apt-bot"

# Clone the git repository of meilix project (the gh-pages branch only)
git clone -b gh-pages --single-branch https://apt-bot:$APT_SOURCE_UPDATER@github.com/fossasia/meilix.git

# Switching branch
git checkout gh-pages

# Copy the contents from the four folders and force replace them with the current
cp -rf ../conf ./meilix/
cp -rf ../db ./meilix/
cp -rf ../dists ./meilix/
cp -rf ../incoming ./meilix/
cp -rf ../pool ./meilix/

# Adding everything
git add .

# Checking for staged changes
git status --porcelain|grep "M"
# if there are changes
if [ "$?" = 0 ]; then
  git commit --message "Apt source update for build:$TRAVIS_BUILD_NUMBER | Generated by Travis CI"
  git remote add origin-pages https://apt-bot:$APT_SOURCE_UPDATER@github.com/fossasia/meilix.git
  git pull --rebase origin-pages gh-pages
  git push --quiet --set-upstream origin-pages gh-pages
  echo "Commit has been made, Happy coding :)"
else
  echo "No changes detected.... Not commiting... Happy coding :)"
fi
